-- Sequence and defined type
CREATE SEQUENCE IF NOT EXISTS trending_positions_id_seq;

-- Table Definition
CREATE TABLE "public"."trending_positions" (
    "id" int4 NOT NULL DEFAULT nextval('trending_positions_id_seq'::regclass),
    "track_position_url" text,
    "track_pool_url" text,
    "name" text,
    "pool_tvl" numeric,
    "range" text,
    "duration_hours" numeric,
    "avg_aum" numeric,
    "apr" numeric,
    "aum" numeric,
    "pnl" numeric,
    "roi" numeric,
    "yield" numeric,
    "is_bot_contract" bool,
    "manager_account" text,
    "source_identifier" text,
    "owner_is_contract" bool,
    "token_id_owner" text,
    "total_deposited" numeric,
    "total_withdrawn" numeric,
    "collected_fees" numeric,
    "uncollected_fees" numeric,
    "collected_rewards" numeric,
    "uncollected_rewards" numeric,
    "chain_name" text,
    "chain_id" int8,
    "protocol" text,
    "position_manager" text,
    "collect_address" text,
    "pool_address" text,
    "pool_fee" numeric,
    "type" text,
    "tick_spacing" int8,
    "tick_lower" int8,
    "tick_upper" int8,
    "current_tick" int8,
    "symbol_t0" text,
    "address_t0" text,
    "symbol_t1" text,
    "address_t1" text,
    "decimals_t0" int4,
    "decimals_t1" int4,
    "amount_t0" numeric,
    "amount_t1" numeric,
    "amount_t0_price_eth" numeric,
    "amount_t1_price_eth" numeric,
    "token0_price_eth" numeric,
    "token1_price_eth" numeric,
    "symbol_reward_t" text,
    "address_reward_t" text,
    "reward_token_price_eth" numeric,
    "events" jsonb,
    "combined_raw_events" jsonb,
    "duration_seconds" int8,
    "snapshot_block" int8,
    "snapshot_timestamp" int8,
    "open_time" text,
    "is_closed" bool,
    "token_id" int8,
    PRIMARY KEY ("id")
);


-- Indices
CREATE UNIQUE INDEX trending_positions_unique_key ON public.trending_positions USING btree (token_id, chain_id, position_manager);